version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/etc/redis:/root/redis
      - /usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=secret
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nest:
    image: node:latest
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: "npm run start"
